name: social_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  conditional_builder: ^1.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  dio: ^4.0.0
  hexcolor: ^2.0.3
  shared_preferences: ^2.0.6
  smooth_page_indicator: ^0.2.3
  #smooth_page_indicator package to customize animated page indicator with a set of built-in effects  in onBoarding_screen my app
  fluttertoast: ^8.0.7
  image_picker: ^0.8.1+1

  #firebase_packages
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  firebase_messaging: ^10.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/oswald.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf


